### PR TITLE
Sanitize filepath for hashing

### LINKED ISSUE #10: Baseline currently depends on Directory-separator
Thanks for the amazing project! It really helps in linting a grown project 😁 

What we though found out (the hard way) is that right now the baseline relies upon the hash which contains the path of the analysed file. This breaks in teams whith mixed development environments as a baseline created on Linux (`/`as directory separator) doesn'T work on Windows (`\` as directory separator).

We are currently working on a fix for that by normalizing the path before creating the hash - in essence replacing the windows separator with a linux separator.

I am not thinking that it makes sense to also consider the colon from the classic MacOS as separator.

### PR DESCRIPTION
**Pull request by heiglandreas**
To generate a hash that can both be used on windows as well as on *nix based systems this commit replaces the backslash directory separator with a forward-slash separator.

We leave it in the `path` attribute to not interfere with other tools that might depend on it.

**CAVEAT** This will break baselines for Windows-Users! The hashing should be backwards-compatible on *nix platforms but will break on Windows as the windows-path will be sanitized and therefore the hash will change.

Fixes #10

### CODE REVIEW

File: src/eslint.js [hunk 1]
```diff
@@ -39,6 +39,8 @@ async function execute(args = []) {
             if (message.severity >= 2) {
 
                 let filePath = path.relative(process.cwd(), file.filePath);
+                const sanitizedfilePath = filePath.replace('\\\\', '/');
```
Comment (Seldaek) [inline src/eslint.js:42]: For safety I'd probably replace with a regex /(\\\\)+/ into /, so that it supports two or 4 (or 6..) backslashes

Comment (heiglandreas) [inline src/eslint.js:42]:
```suggestion
                const sanitizedfilePath = filePath.replace(/(\\)+/', '/');
```

**Review by Seldaek — APPROVED** [review]

**Comment by JasonEleventeen** [comment]
@Humni

**Review by JasonEleventeen — APPROVED** [review]
lgtm

**Comment by Humni** [comment]
Thanks for this - definitely a required improvement when you have teams working cross platform. Decided this will just be a minor version bump as a regenerate is straightforward despite the requirement to regenerate on windows. Most CI/CD environments will be on *nix too so automated environments should be okay.
